package com.stannis

import com.stannis.parser.fileHandler.LogicHandler

fun main() {

    val projectPath =
        "/home/stan/Desktop/Licenta/src/main/resources/ConsoleApplication1"

    LogicHandler.run(projectPath, listOf("oop"))
    /*
    -oop
    generates a serialized file with the important things from an oop
    point of view.

    - parse
     the files and the hierarchy of project directories are generated.
     .json files contain tokens generated by cdt

     */
}
