package com.stannis

import com.stannis.parser.fileHandler.LogicHandler
import mu.KotlinLogging

fun main(args: Array<String>) {
    val projectPath = args[0]
    when (args.size) {
        2 -> {
            LogicHandler.run(projectPath, listOf(args[1]))
        }
        3 -> {
            LogicHandler.run(projectPath, listOf(args[1], args[2]))
        }
        else -> {
            val logger = KotlinLogging.logger {}
            logger.info { "Arguments error" }
            logger.info { "example: <Path> <List of Supported types>" }
            logger.info {
                "\"-oop\\ngenerates a serialized file with the important things from an oop\\npoint of view.\""
            }
            logger.info {
                "- parse\n" +
                        "     the files and the hierarchy of project directories are generated.\n" +
                        "     .json files contain tokens generated by cdt\n"
            }
        }
    }
    /*
    -oop
    generates a serialized file with the important things from an oop
    point of view.

    - parse
     the files and the hierarchy of project directories are generated.
     .json files contain tokens generated by cdt
     */
}
